#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : wireshark
Version  : 4.4.3
Release  : 122
URL      : https://2.na.dl.wireshark.org/src/wireshark-4.4.3.tar.xz
Source0  : https://2.na.dl.wireshark.org/src/wireshark-4.4.3.tar.xz
Summary  : Generate parsers / DCE/RPC-clients from IDL
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 GPL-3.0 ISC MIT
Requires: wireshark-bin = %{version}-%{release}
Requires: wireshark-data = %{version}-%{release}
Requires: wireshark-lib = %{version}-%{release}
Requires: wireshark-license = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : buildreq-qt6
BuildRequires : c-ares-dev
BuildRequires : collectd-dev
BuildRequires : doxygen
BuildRequires : extra-cmake-modules
BuildRequires : flex
BuildRequires : gettext-dev
BuildRequires : git
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : libmaxminddb-dev
BuildRequires : libpcap-dev
BuildRequires : libxml2-dev
BuildRequires : lua-dev
BuildRequires : nghttp2-dev
BuildRequires : opus-dev
BuildRequires : opusfile-dev
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(com_err)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(krb5)
BuildRequires : pkgconfig(libcap)
BuildRequires : pkgconfig(libcares)
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(libnl-3.0)
BuildRequires : pkgconfig(libnl-genl-3.0)
BuildRequires : pkgconfig(libnl-route-3.0)
BuildRequires : pkgconfig(libssh)
BuildRequires : pkgconfig(libtiff-4)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(lua)
BuildRequires : pkgconfig(portaudio-2.0)
BuildRequires : pypi-pytest
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : qt5compat-dev
BuildRequires : qt6base-dev
BuildRequires : qttools-dev
BuildRequires : sbc-dev
BuildRequires : snappy-dev
BuildRequires : speexdsp-dev
BuildRequires : systemd-dev
BuildRequires : tiff-dev
BuildRequires : wireshark
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0002-ignore-clobber.patch

%description
This is an example of how to build a Wireshark plugin out-of-tree. This
is an alternative, more recent way to build Wireshark binary plugins,
include a new plugin into the project source tree (here called in-tree
build). Building a plugin out-of-tree doesn't require rebuilding the whole
Wireshark source tree every time.

%package bin
Summary: bin components for the wireshark package.
Group: Binaries
Requires: wireshark-data = %{version}-%{release}
Requires: wireshark-license = %{version}-%{release}

%description bin
bin components for the wireshark package.


%package data
Summary: data components for the wireshark package.
Group: Data

%description data
data components for the wireshark package.


%package dev
Summary: dev components for the wireshark package.
Group: Development
Requires: wireshark-lib = %{version}-%{release}
Requires: wireshark-bin = %{version}-%{release}
Requires: wireshark-data = %{version}-%{release}
Provides: wireshark-devel = %{version}-%{release}
Requires: wireshark = %{version}-%{release}

%description dev
dev components for the wireshark package.


%package doc
Summary: doc components for the wireshark package.
Group: Documentation

%description doc
doc components for the wireshark package.


%package lib
Summary: lib components for the wireshark package.
Group: Libraries
Requires: wireshark-data = %{version}-%{release}
Requires: wireshark-license = %{version}-%{release}

%description lib
lib components for the wireshark package.


%package license
Summary: license components for the wireshark package.
Group: Default

%description license
license components for the wireshark package.


%prep
%setup -q -n wireshark-4.4.3
cd %{_builddir}/wireshark-4.4.3
%patch -P 1 -p1
pushd ..
cp -a wireshark-4.4.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1736436961
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DENABLE_LUA=OFF  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DENABLE_LUA=OFF  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make %{?_smp_mflags} test || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1736436961
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/wireshark
cp %{_builddir}/wireshark-%{version}/COPYING %{buildroot}/usr/share/package-licenses/wireshark/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/wireshark-%{version}/cmake/modules/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/wireshark/fad0e142195689a22e56df66f20dbd840679adb9 || :
cp %{_builddir}/wireshark-%{version}/cmake/modules/LICENSE.txt %{buildroot}/usr/share/package-licenses/wireshark/6a24215d6bbdeb8e9b97926525bcf1958dda4e86 || :
cp %{_builddir}/wireshark-%{version}/epan/dissectors/pidl/IDL_LICENSE.txt %{buildroot}/usr/share/package-licenses/wireshark/41bb27089429d9d6febf18e4237cf04d81fcc737 || :
cp %{_builddir}/wireshark-%{version}/epan/wslua/lrexlib/LICENSE %{buildroot}/usr/share/package-licenses/wireshark/212440a7e42ecceff52496bfd595bd23cea67d05 || :
cp %{_builddir}/wireshark-%{version}/packaging/debian/copyright %{buildroot}/usr/share/package-licenses/wireshark/95e0d72b02cd8da759ea37b4b9dd8c759c5cad72 || :
cp %{_builddir}/wireshark-%{version}/packaging/wix/COPYING.rtf %{buildroot}/usr/share/package-licenses/wireshark/a20d2f6f5e7e9eb06617df3b88af6192a8147307 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib64/wireshark/extcap/androiddump
/V3/usr/lib64/wireshark/extcap/ciscodump
/V3/usr/lib64/wireshark/extcap/dpauxmon
/V3/usr/lib64/wireshark/extcap/randpktdump
/V3/usr/lib64/wireshark/extcap/sdjournal
/V3/usr/lib64/wireshark/extcap/sshdump
/V3/usr/lib64/wireshark/extcap/udpdump
/V3/usr/lib64/wireshark/extcap/wifidump
/usr/lib64/wireshark/extcap/androiddump
/usr/lib64/wireshark/extcap/ciscodump
/usr/lib64/wireshark/extcap/dpauxmon
/usr/lib64/wireshark/extcap/randpktdump
/usr/lib64/wireshark/extcap/sdjournal
/usr/lib64/wireshark/extcap/sshdump
/usr/lib64/wireshark/extcap/udpdump
/usr/lib64/wireshark/extcap/wifidump

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/capinfos
/V3/usr/bin/captype
/V3/usr/bin/dumpcap
/V3/usr/bin/editcap
/V3/usr/bin/idl2wrs
/V3/usr/bin/mergecap
/V3/usr/bin/mmdbresolve
/V3/usr/bin/randpkt
/V3/usr/bin/rawshark
/V3/usr/bin/reordercap
/V3/usr/bin/sharkd
/V3/usr/bin/text2pcap
/V3/usr/bin/tshark
/V3/usr/bin/wireshark
/usr/bin/capinfos
/usr/bin/captype
/usr/bin/dumpcap
/usr/bin/editcap
/usr/bin/idl2wrs
/usr/bin/mergecap
/usr/bin/mmdbresolve
/usr/bin/randpkt
/usr/bin/rawshark
/usr/bin/reordercap
/usr/bin/sharkd
/usr/bin/text2pcap
/usr/bin/tshark
/usr/bin/wireshark

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.wireshark.Wireshark.desktop
/usr/share/icons/hicolor/128x128/apps/org.wireshark.Wireshark.png
/usr/share/icons/hicolor/128x128/mimetypes/org.wireshark.Wireshark-mimetype.png
/usr/share/icons/hicolor/16x16/apps/org.wireshark.Wireshark.png
/usr/share/icons/hicolor/16x16/mimetypes/org.wireshark.Wireshark-mimetype.png
/usr/share/icons/hicolor/24x24/apps/org.wireshark.Wireshark.png
/usr/share/icons/hicolor/24x24/mimetypes/org.wireshark.Wireshark-mimetype.png
/usr/share/icons/hicolor/256x256/apps/org.wireshark.Wireshark.png
/usr/share/icons/hicolor/256x256/mimetypes/org.wireshark.Wireshark-mimetype.png
/usr/share/icons/hicolor/32x32/apps/org.wireshark.Wireshark.png
/usr/share/icons/hicolor/32x32/mimetypes/org.wireshark.Wireshark-mimetype.png
/usr/share/icons/hicolor/48x48/apps/org.wireshark.Wireshark.png
/usr/share/icons/hicolor/48x48/mimetypes/org.wireshark.Wireshark-mimetype.png
/usr/share/icons/hicolor/64x64/apps/org.wireshark.Wireshark.png
/usr/share/icons/hicolor/64x64/mimetypes/org.wireshark.Wireshark-mimetype.png
/usr/share/metainfo/org.wireshark.Wireshark.metainfo.xml
/usr/share/mime-packages/org.wireshark.Wireshark.xml
/usr/share/wireshark/cfilters
/usr/share/wireshark/colorfilters
/usr/share/wireshark/dfilters
/usr/share/wireshark/diameter/AlcatelLucent.xml
/usr/share/wireshark/diameter/Cisco.xml
/usr/share/wireshark/diameter/CiscoSystems.xml
/usr/share/wireshark/diameter/Custom.xml
/usr/share/wireshark/diameter/Ericsson.xml
/usr/share/wireshark/diameter/HP.xml
/usr/share/wireshark/diameter/Huawei.xml
/usr/share/wireshark/diameter/Inovar.xml
/usr/share/wireshark/diameter/Juniper.xml
/usr/share/wireshark/diameter/Metaswitch.xml
/usr/share/wireshark/diameter/Microsoft.xml
/usr/share/wireshark/diameter/Nokia.xml
/usr/share/wireshark/diameter/NokiaSolutionsAndNetworks.xml
/usr/share/wireshark/diameter/Oracle.xml
/usr/share/wireshark/diameter/Siemens.xml
/usr/share/wireshark/diameter/Starent.xml
/usr/share/wireshark/diameter/TGPP.xml
/usr/share/wireshark/diameter/TGPP2.xml
/usr/share/wireshark/diameter/Telefonica.xml
/usr/share/wireshark/diameter/Travelping.xml
/usr/share/wireshark/diameter/VerizonWireless.xml
/usr/share/wireshark/diameter/Vodafone.xml
/usr/share/wireshark/diameter/chargecontrol.xml
/usr/share/wireshark/diameter/dictionary.dtd
/usr/share/wireshark/diameter/dictionary.xml
/usr/share/wireshark/diameter/eap.xml
/usr/share/wireshark/diameter/etsie2e4.xml
/usr/share/wireshark/diameter/mobileipv4.xml
/usr/share/wireshark/diameter/mobileipv6.xml
/usr/share/wireshark/diameter/nasreq.xml
/usr/share/wireshark/diameter/sip.xml
/usr/share/wireshark/diameter/sunping.xml
/usr/share/wireshark/dmacros
/usr/share/wireshark/dtds/dc.dtd
/usr/share/wireshark/dtds/itunes.dtd
/usr/share/wireshark/dtds/mscml.dtd
/usr/share/wireshark/dtds/pocsettings.dtd
/usr/share/wireshark/dtds/presence.dtd
/usr/share/wireshark/dtds/reginfo.dtd
/usr/share/wireshark/dtds/rlmi.dtd
/usr/share/wireshark/dtds/rss.dtd
/usr/share/wireshark/dtds/smil.dtd
/usr/share/wireshark/dtds/watcherinfo.dtd
/usr/share/wireshark/dtds/xcap-caps.dtd
/usr/share/wireshark/dtds/xcap-error.dtd
/usr/share/wireshark/ipmap.html
/usr/share/wireshark/profiles/Bluetooth/colorfilters
/usr/share/wireshark/profiles/Bluetooth/preferences
/usr/share/wireshark/profiles/Classic/colorfilters
"/usr/share/wireshark/profiles/No Reassembly/preferences"
/usr/share/wireshark/radius/.editorconfig
/usr/share/wireshark/radius/README.radius_dictionary
/usr/share/wireshark/radius/custom.includes
/usr/share/wireshark/radius/dictionary
/usr/share/wireshark/radius/dictionary.3com
/usr/share/wireshark/radius/dictionary.3gpp
/usr/share/wireshark/radius/dictionary.3gpp2
/usr/share/wireshark/radius/dictionary.5x9
/usr/share/wireshark/radius/dictionary.acc
/usr/share/wireshark/radius/dictionary.acme
/usr/share/wireshark/radius/dictionary.actelis
/usr/share/wireshark/radius/dictionary.adtran
/usr/share/wireshark/radius/dictionary.adva
/usr/share/wireshark/radius/dictionary.aerohive
/usr/share/wireshark/radius/dictionary.airespace
/usr/share/wireshark/radius/dictionary.alcatel
/usr/share/wireshark/radius/dictionary.alcatel-lucent.aaa
/usr/share/wireshark/radius/dictionary.alcatel.esam
/usr/share/wireshark/radius/dictionary.alcatel.sr
/usr/share/wireshark/radius/dictionary.alphion
/usr/share/wireshark/radius/dictionary.alteon
/usr/share/wireshark/radius/dictionary.altiga
/usr/share/wireshark/radius/dictionary.alvarion
/usr/share/wireshark/radius/dictionary.alvarion.wimax.v2_2
/usr/share/wireshark/radius/dictionary.apc
/usr/share/wireshark/radius/dictionary.aptilo
/usr/share/wireshark/radius/dictionary.aptis
/usr/share/wireshark/radius/dictionary.arbor
/usr/share/wireshark/radius/dictionary.arista
/usr/share/wireshark/radius/dictionary.aruba
/usr/share/wireshark/radius/dictionary.ascend
/usr/share/wireshark/radius/dictionary.ascend.illegal
/usr/share/wireshark/radius/dictionary.asn
/usr/share/wireshark/radius/dictionary.audiocodes
/usr/share/wireshark/radius/dictionary.avaya
/usr/share/wireshark/radius/dictionary.azaire
/usr/share/wireshark/radius/dictionary.bay
/usr/share/wireshark/radius/dictionary.bigswitch
/usr/share/wireshark/radius/dictionary.bintec
/usr/share/wireshark/radius/dictionary.bluecoat
/usr/share/wireshark/radius/dictionary.boingo
/usr/share/wireshark/radius/dictionary.bristol
/usr/share/wireshark/radius/dictionary.broadsoft
/usr/share/wireshark/radius/dictionary.brocade
/usr/share/wireshark/radius/dictionary.bskyb
/usr/share/wireshark/radius/dictionary.bt
/usr/share/wireshark/radius/dictionary.cablelabs
/usr/share/wireshark/radius/dictionary.cabletron
/usr/share/wireshark/radius/dictionary.calix
/usr/share/wireshark/radius/dictionary.cambium
/usr/share/wireshark/radius/dictionary.camiant
/usr/share/wireshark/radius/dictionary.centec
/usr/share/wireshark/radius/dictionary.checkpoint
/usr/share/wireshark/radius/dictionary.chillispot
/usr/share/wireshark/radius/dictionary.ciena
/usr/share/wireshark/radius/dictionary.cisco
/usr/share/wireshark/radius/dictionary.cisco.asa
/usr/share/wireshark/radius/dictionary.cisco.bbsm
/usr/share/wireshark/radius/dictionary.cisco.vpn3000
/usr/share/wireshark/radius/dictionary.cisco.vpn5000
/usr/share/wireshark/radius/dictionary.citrix
/usr/share/wireshark/radius/dictionary.ckey
/usr/share/wireshark/radius/dictionary.clavister
/usr/share/wireshark/radius/dictionary.cnergee
/usr/share/wireshark/radius/dictionary.colubris
/usr/share/wireshark/radius/dictionary.columbia_university
/usr/share/wireshark/radius/dictionary.compat
/usr/share/wireshark/radius/dictionary.compatible
/usr/share/wireshark/radius/dictionary.cosine
/usr/share/wireshark/radius/dictionary.covaro
/usr/share/wireshark/radius/dictionary.dante
/usr/share/wireshark/radius/dictionary.dellemc
/usr/share/wireshark/radius/dictionary.digium
/usr/share/wireshark/radius/dictionary.dlink
/usr/share/wireshark/radius/dictionary.dragonwave
/usr/share/wireshark/radius/dictionary.efficientip
/usr/share/wireshark/radius/dictionary.eleven
/usr/share/wireshark/radius/dictionary.eltex
/usr/share/wireshark/radius/dictionary.enterasys
/usr/share/wireshark/radius/dictionary.epygi
/usr/share/wireshark/radius/dictionary.equallogic
/usr/share/wireshark/radius/dictionary.ericsson
/usr/share/wireshark/radius/dictionary.ericsson.ab
/usr/share/wireshark/radius/dictionary.ericsson.packet.core.networks
/usr/share/wireshark/radius/dictionary.erx
/usr/share/wireshark/radius/dictionary.extreme
/usr/share/wireshark/radius/dictionary.f5
/usr/share/wireshark/radius/dictionary.fdxtended
/usr/share/wireshark/radius/dictionary.force10
/usr/share/wireshark/radius/dictionary.fortinet
/usr/share/wireshark/radius/dictionary.foundry
/usr/share/wireshark/radius/dictionary.freedhcp
/usr/share/wireshark/radius/dictionary.freeradius
/usr/share/wireshark/radius/dictionary.freeradius.evs5
/usr/share/wireshark/radius/dictionary.freeradius.internal
/usr/share/wireshark/radius/dictionary.freeswitch
/usr/share/wireshark/radius/dictionary.gandalf
/usr/share/wireshark/radius/dictionary.garderos
/usr/share/wireshark/radius/dictionary.gemtek
/usr/share/wireshark/radius/dictionary.h3c
/usr/share/wireshark/radius/dictionary.hillstone
/usr/share/wireshark/radius/dictionary.hp
/usr/share/wireshark/radius/dictionary.huawei
/usr/share/wireshark/radius/dictionary.iana
/usr/share/wireshark/radius/dictionary.identity_engines
/usr/share/wireshark/radius/dictionary.iea
/usr/share/wireshark/radius/dictionary.infinera
/usr/share/wireshark/radius/dictionary.infoblox
/usr/share/wireshark/radius/dictionary.infonet
/usr/share/wireshark/radius/dictionary.ipunplugged
/usr/share/wireshark/radius/dictionary.issanni
/usr/share/wireshark/radius/dictionary.itk
/usr/share/wireshark/radius/dictionary.jradius
/usr/share/wireshark/radius/dictionary.juniper
/usr/share/wireshark/radius/dictionary.karlnet
/usr/share/wireshark/radius/dictionary.kineto
/usr/share/wireshark/radius/dictionary.lancom
/usr/share/wireshark/radius/dictionary.lantronix
/usr/share/wireshark/radius/dictionary.livingston
/usr/share/wireshark/radius/dictionary.localweb
/usr/share/wireshark/radius/dictionary.lucent
/usr/share/wireshark/radius/dictionary.manzara
/usr/share/wireshark/radius/dictionary.meinberg
/usr/share/wireshark/radius/dictionary.mellanox
/usr/share/wireshark/radius/dictionary.meraki
/usr/share/wireshark/radius/dictionary.merit
/usr/share/wireshark/radius/dictionary.meru
/usr/share/wireshark/radius/dictionary.microsemi
/usr/share/wireshark/radius/dictionary.microsoft
/usr/share/wireshark/radius/dictionary.mikrotik
/usr/share/wireshark/radius/dictionary.mimosa
/usr/share/wireshark/radius/dictionary.motorola
/usr/share/wireshark/radius/dictionary.motorola.illegal
/usr/share/wireshark/radius/dictionary.motorola.wimax
/usr/share/wireshark/radius/dictionary.navini
/usr/share/wireshark/radius/dictionary.net
/usr/share/wireshark/radius/dictionary.netelastic
/usr/share/wireshark/radius/dictionary.netscreen
/usr/share/wireshark/radius/dictionary.networkphysics
/usr/share/wireshark/radius/dictionary.nexans
/usr/share/wireshark/radius/dictionary.nile
/usr/share/wireshark/radius/dictionary.nokia
/usr/share/wireshark/radius/dictionary.nokia.conflict
/usr/share/wireshark/radius/dictionary.nomadix
/usr/share/wireshark/radius/dictionary.nortel
/usr/share/wireshark/radius/dictionary.ntua
/usr/share/wireshark/radius/dictionary.openser
/usr/share/wireshark/radius/dictionary.openwifi
/usr/share/wireshark/radius/dictionary.packeteer
/usr/share/wireshark/radius/dictionary.paloalto
/usr/share/wireshark/radius/dictionary.patton
/usr/share/wireshark/radius/dictionary.perle
/usr/share/wireshark/radius/dictionary.pfsense
/usr/share/wireshark/radius/dictionary.pica8
/usr/share/wireshark/radius/dictionary.propel
/usr/share/wireshark/radius/dictionary.prosoft
/usr/share/wireshark/radius/dictionary.proxim
/usr/share/wireshark/radius/dictionary.purewave
/usr/share/wireshark/radius/dictionary.quiconnect
/usr/share/wireshark/radius/dictionary.quintum
/usr/share/wireshark/radius/dictionary.rcntec
/usr/share/wireshark/radius/dictionary.redcreek
/usr/share/wireshark/radius/dictionary.rfc2865
/usr/share/wireshark/radius/dictionary.rfc2866
/usr/share/wireshark/radius/dictionary.rfc2867
/usr/share/wireshark/radius/dictionary.rfc2868
/usr/share/wireshark/radius/dictionary.rfc2869
/usr/share/wireshark/radius/dictionary.rfc3162
/usr/share/wireshark/radius/dictionary.rfc3576
/usr/share/wireshark/radius/dictionary.rfc3580
/usr/share/wireshark/radius/dictionary.rfc4072
/usr/share/wireshark/radius/dictionary.rfc4372
/usr/share/wireshark/radius/dictionary.rfc4603
/usr/share/wireshark/radius/dictionary.rfc4675
/usr/share/wireshark/radius/dictionary.rfc4679
/usr/share/wireshark/radius/dictionary.rfc4818
/usr/share/wireshark/radius/dictionary.rfc4849
/usr/share/wireshark/radius/dictionary.rfc5090
/usr/share/wireshark/radius/dictionary.rfc5176
/usr/share/wireshark/radius/dictionary.rfc5447
/usr/share/wireshark/radius/dictionary.rfc5580
/usr/share/wireshark/radius/dictionary.rfc5607
/usr/share/wireshark/radius/dictionary.rfc5904
/usr/share/wireshark/radius/dictionary.rfc6519
/usr/share/wireshark/radius/dictionary.rfc6572
/usr/share/wireshark/radius/dictionary.rfc6677
/usr/share/wireshark/radius/dictionary.rfc6911
/usr/share/wireshark/radius/dictionary.rfc6929
/usr/share/wireshark/radius/dictionary.rfc6930
/usr/share/wireshark/radius/dictionary.rfc7055
/usr/share/wireshark/radius/dictionary.rfc7155
/usr/share/wireshark/radius/dictionary.rfc7268
/usr/share/wireshark/radius/dictionary.rfc7499
/usr/share/wireshark/radius/dictionary.rfc7930
/usr/share/wireshark/radius/dictionary.rfc8045
/usr/share/wireshark/radius/dictionary.rfc8559
/usr/share/wireshark/radius/dictionary.riverbed
/usr/share/wireshark/radius/dictionary.riverstone
/usr/share/wireshark/radius/dictionary.roaringpenguin
/usr/share/wireshark/radius/dictionary.ruckus
/usr/share/wireshark/radius/dictionary.ruggedcom
/usr/share/wireshark/radius/dictionary.sangoma
/usr/share/wireshark/radius/dictionary.sg
/usr/share/wireshark/radius/dictionary.shasta
/usr/share/wireshark/radius/dictionary.shiva
/usr/share/wireshark/radius/dictionary.siemens
/usr/share/wireshark/radius/dictionary.slipstream
/usr/share/wireshark/radius/dictionary.smartsharesystems
/usr/share/wireshark/radius/dictionary.sofaware
/usr/share/wireshark/radius/dictionary.softbank
/usr/share/wireshark/radius/dictionary.sonicwall
/usr/share/wireshark/radius/dictionary.springtide
/usr/share/wireshark/radius/dictionary.starent
/usr/share/wireshark/radius/dictionary.starent.vsa1
/usr/share/wireshark/radius/dictionary.surfnet
/usr/share/wireshark/radius/dictionary.symbol
/usr/share/wireshark/radius/dictionary.t_systems_nova
/usr/share/wireshark/radius/dictionary.telebit
/usr/share/wireshark/radius/dictionary.telkom
/usr/share/wireshark/radius/dictionary.telrad
/usr/share/wireshark/radius/dictionary.terena
/usr/share/wireshark/radius/dictionary.tplink
/usr/share/wireshark/radius/dictionary.trapeze
/usr/share/wireshark/radius/dictionary.travelping
/usr/share/wireshark/radius/dictionary.tripplite
/usr/share/wireshark/radius/dictionary.tropos
/usr/share/wireshark/radius/dictionary.ukerna
/usr/share/wireshark/radius/dictionary.unisphere
/usr/share/wireshark/radius/dictionary.unix
/usr/share/wireshark/radius/dictionary.usr
/usr/share/wireshark/radius/dictionary.usr.illegal
/usr/share/wireshark/radius/dictionary.utstarcom
/usr/share/wireshark/radius/dictionary.valemount
/usr/share/wireshark/radius/dictionary.vasexperts
/usr/share/wireshark/radius/dictionary.verizon
/usr/share/wireshark/radius/dictionary.versanet
/usr/share/wireshark/radius/dictionary.walabi
/usr/share/wireshark/radius/dictionary.waverider
/usr/share/wireshark/radius/dictionary.wichorus
/usr/share/wireshark/radius/dictionary.wifialliance
/usr/share/wireshark/radius/dictionary.wimax
/usr/share/wireshark/radius/dictionary.wimax.alvarion
/usr/share/wireshark/radius/dictionary.wimax.wichorus
/usr/share/wireshark/radius/dictionary.wispr
/usr/share/wireshark/radius/dictionary.xedia
/usr/share/wireshark/radius/dictionary.xylan
/usr/share/wireshark/radius/dictionary.yubico
/usr/share/wireshark/radius/dictionary.zeus
/usr/share/wireshark/radius/dictionary.zte
/usr/share/wireshark/radius/dictionary.zyxel
/usr/share/wireshark/smi_modules
/usr/share/wireshark/tpncp/tpncp.dat
/usr/share/wireshark/wimaxasncp/dictionary.dtd
/usr/share/wireshark/wimaxasncp/dictionary.xml
/usr/share/wireshark/wka

%files dev
%defattr(-,root,root,-)
/usr/lib64/libwireshark.so
/usr/lib64/libwiretap.so
/usr/lib64/libwsutil.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/wireshark/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libwireshark.so.18.0.3
/V3/usr/lib64/libwiretap.so.15.0.3
/V3/usr/lib64/libwsutil.so.16.0.0
/V3/usr/lib64/wireshark/plugins/4.4/codecs/g711.so
/V3/usr/lib64/wireshark/plugins/4.4/codecs/l16mono.so
/V3/usr/lib64/wireshark/plugins/4.4/codecs/opus_dec.so
/V3/usr/lib64/wireshark/plugins/4.4/codecs/sbc.so
/V3/usr/lib64/wireshark/plugins/4.4/epan/ethercat.so
/V3/usr/lib64/wireshark/plugins/4.4/epan/gryphon.so
/V3/usr/lib64/wireshark/plugins/4.4/epan/ipaddr.so
/V3/usr/lib64/wireshark/plugins/4.4/epan/irda.so
/V3/usr/lib64/wireshark/plugins/4.4/epan/mate.so
/V3/usr/lib64/wireshark/plugins/4.4/epan/opcua.so
/V3/usr/lib64/wireshark/plugins/4.4/epan/profinet.so
/V3/usr/lib64/wireshark/plugins/4.4/epan/stats_tree.so
/V3/usr/lib64/wireshark/plugins/4.4/epan/transum.so
/V3/usr/lib64/wireshark/plugins/4.4/epan/unistim.so
/V3/usr/lib64/wireshark/plugins/4.4/epan/wimax.so
/V3/usr/lib64/wireshark/plugins/4.4/epan/wimaxasncp.so
/V3/usr/lib64/wireshark/plugins/4.4/epan/wimaxmacphy.so
/V3/usr/lib64/wireshark/plugins/4.4/wiretap/usbdump.so
/usr/lib64/libwireshark.so.18
/usr/lib64/libwireshark.so.18.0.3
/usr/lib64/libwiretap.so.15
/usr/lib64/libwiretap.so.15.0.3
/usr/lib64/libwsutil.so.16
/usr/lib64/libwsutil.so.16.0.0
/usr/lib64/wireshark/plugins/4.4/codecs/g711.so
/usr/lib64/wireshark/plugins/4.4/codecs/l16mono.so
/usr/lib64/wireshark/plugins/4.4/codecs/opus_dec.so
/usr/lib64/wireshark/plugins/4.4/codecs/sbc.so
/usr/lib64/wireshark/plugins/4.4/epan/ethercat.so
/usr/lib64/wireshark/plugins/4.4/epan/gryphon.so
/usr/lib64/wireshark/plugins/4.4/epan/ipaddr.so
/usr/lib64/wireshark/plugins/4.4/epan/irda.so
/usr/lib64/wireshark/plugins/4.4/epan/mate.so
/usr/lib64/wireshark/plugins/4.4/epan/opcua.so
/usr/lib64/wireshark/plugins/4.4/epan/profinet.so
/usr/lib64/wireshark/plugins/4.4/epan/stats_tree.so
/usr/lib64/wireshark/plugins/4.4/epan/transum.so
/usr/lib64/wireshark/plugins/4.4/epan/unistim.so
/usr/lib64/wireshark/plugins/4.4/epan/wimax.so
/usr/lib64/wireshark/plugins/4.4/epan/wimaxasncp.so
/usr/lib64/wireshark/plugins/4.4/epan/wimaxmacphy.so
/usr/lib64/wireshark/plugins/4.4/wiretap/usbdump.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/wireshark/212440a7e42ecceff52496bfd595bd23cea67d05
/usr/share/package-licenses/wireshark/41bb27089429d9d6febf18e4237cf04d81fcc737
/usr/share/package-licenses/wireshark/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/wireshark/6a24215d6bbdeb8e9b97926525bcf1958dda4e86
/usr/share/package-licenses/wireshark/95e0d72b02cd8da759ea37b4b9dd8c759c5cad72
/usr/share/package-licenses/wireshark/a20d2f6f5e7e9eb06617df3b88af6192a8147307
/usr/share/package-licenses/wireshark/fad0e142195689a22e56df66f20dbd840679adb9
