#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wireshark
Version  : 4.0.0
Release  : 71
URL      : https://1.na.dl.wireshark.org/src/wireshark-4.0.0.tar.xz
Source0  : https://1.na.dl.wireshark.org/src/wireshark-4.0.0.tar.xz
Summary  : Generate parsers / DCE/RPC-clients from IDL
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 GPL-3.0 ISC
Requires: wireshark-bin = %{version}-%{release}
Requires: wireshark-data = %{version}-%{release}
Requires: wireshark-lib = %{version}-%{release}
Requires: wireshark-license = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-cmake
BuildRequires : buildreq-cpan
BuildRequires : buildreq-kde
BuildRequires : collectd-dev
BuildRequires : compat-lua-52-dev
BuildRequires : compat-lua-52-staticdev
BuildRequires : doxygen
BuildRequires : extra-cmake-modules pkgconfig(glib-2.0)
BuildRequires : flex
BuildRequires : gettext-dev
BuildRequires : git
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : libmaxminddb-dev
BuildRequires : libpcap-dev
BuildRequires : libxml2-dev
BuildRequires : nghttp2-dev
BuildRequires : opus-dev
BuildRequires : opusfile-dev
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(com_err)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(krb5)
BuildRequires : pkgconfig(libcap)
BuildRequires : pkgconfig(libcares)
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(libnl-3.0)
BuildRequires : pkgconfig(libnl-genl-3.0)
BuildRequires : pkgconfig(libnl-route-3.0)
BuildRequires : pkgconfig(libssh)
BuildRequires : pkgconfig(libtiff-4)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(lua)
BuildRequires : pkgconfig(lua52)
BuildRequires : pkgconfig(portaudio-2.0)
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : qt6base-dev
BuildRequires : qttools-dev
BuildRequires : sbc-dev
BuildRequires : snappy-dev
BuildRequires : speexdsp-dev
BuildRequires : systemd-dev
BuildRequires : tiff-dev
BuildRequires : wireshark
BuildRequires : zlib-dev
Patch1: 0002-ignore-clobber.patch

%description
NOTE: this documents the original intent behind libwiretap.  Currently,
it is being developed solely as a library for reading capture files,
rather than packet capture.  The list of file formats is also
out-of-date.

%package bin
Summary: bin components for the wireshark package.
Group: Binaries
Requires: wireshark-data = %{version}-%{release}
Requires: wireshark-license = %{version}-%{release}

%description bin
bin components for the wireshark package.


%package data
Summary: data components for the wireshark package.
Group: Data

%description data
data components for the wireshark package.


%package dev
Summary: dev components for the wireshark package.
Group: Development
Requires: wireshark-lib = %{version}-%{release}
Requires: wireshark-bin = %{version}-%{release}
Requires: wireshark-data = %{version}-%{release}
Provides: wireshark-devel = %{version}-%{release}
Requires: wireshark = %{version}-%{release}

%description dev
dev components for the wireshark package.


%package lib
Summary: lib components for the wireshark package.
Group: Libraries
Requires: wireshark-data = %{version}-%{release}
Requires: wireshark-license = %{version}-%{release}

%description lib
lib components for the wireshark package.


%package license
Summary: license components for the wireshark package.
Group: Default

%description license
license components for the wireshark package.


%prep
%setup -q -n wireshark-4.0.0
cd %{_builddir}/wireshark-4.0.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664989273
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make %{?_smp_mflags} test || :

%install
export SOURCE_DATE_EPOCH=1664989273
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/wireshark
cp %{_builddir}/wireshark-%{version}/COPYING %{buildroot}/usr/share/package-licenses/wireshark/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/wireshark-%{version}/cmake/modules/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/wireshark/fad0e142195689a22e56df66f20dbd840679adb9 || :
cp %{_builddir}/wireshark-%{version}/cmake/modules/LICENSE.txt %{buildroot}/usr/share/package-licenses/wireshark/6a24215d6bbdeb8e9b97926525bcf1958dda4e86 || :
cp %{_builddir}/wireshark-%{version}/epan/dissectors/pidl/IDL_LICENSE.txt %{buildroot}/usr/share/package-licenses/wireshark/41bb27089429d9d6febf18e4237cf04d81fcc737 || :
cp %{_builddir}/wireshark-%{version}/packaging/debian/copyright %{buildroot}/usr/share/package-licenses/wireshark/95e0d72b02cd8da759ea37b4b9dd8c759c5cad72 || :
cp %{_builddir}/wireshark-%{version}/packaging/wix/COPYING.rtf %{buildroot}/usr/share/package-licenses/wireshark/a20d2f6f5e7e9eb06617df3b88af6192a8147307 || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib64/wireshark/cmake/FindGLIB2.cmake
/usr/lib64/wireshark/cmake/FindWSLibrary.cmake
/usr/lib64/wireshark/cmake/FindWSWinLibs.cmake
/usr/lib64/wireshark/cmake/LocatePythonModule.cmake
/usr/lib64/wireshark/cmake/UseAsn2Wrs.cmake
/usr/lib64/wireshark/cmake/UseMakePluginReg.cmake
/usr/lib64/wireshark/cmake/WiresharkConfig.cmake
/usr/lib64/wireshark/cmake/WiresharkConfigVersion.cmake
/usr/lib64/wireshark/cmake/WiresharkTargets-relwithdebinfo.cmake
/usr/lib64/wireshark/cmake/WiresharkTargets.cmake
/usr/lib64/wireshark/extcap/androiddump
/usr/lib64/wireshark/extcap/ciscodump
/usr/lib64/wireshark/extcap/dpauxmon
/usr/lib64/wireshark/extcap/randpktdump
/usr/lib64/wireshark/extcap/sdjournal
/usr/lib64/wireshark/extcap/sshdump
/usr/lib64/wireshark/extcap/udpdump
/usr/lib64/wireshark/extcap/wifidump

%files bin
%defattr(-,root,root,-)
/usr/bin/capinfos
/usr/bin/captype
/usr/bin/dumpcap
/usr/bin/editcap
/usr/bin/idl2wrs
/usr/bin/mergecap
/usr/bin/mmdbresolve
/usr/bin/randpkt
/usr/bin/rawshark
/usr/bin/reordercap
/usr/bin/sharkd
/usr/bin/text2pcap
/usr/bin/tshark
/usr/bin/wireshark

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.wireshark.Wireshark.desktop
/usr/share/icons/hicolor/128x128/apps/org.wireshark.Wireshark.png
/usr/share/icons/hicolor/128x128/mimetypes/org.wireshark.Wireshark-mimetype.png
/usr/share/icons/hicolor/16x16/apps/org.wireshark.Wireshark.png
/usr/share/icons/hicolor/16x16/mimetypes/org.wireshark.Wireshark-mimetype.png
/usr/share/icons/hicolor/24x24/apps/org.wireshark.Wireshark.png
/usr/share/icons/hicolor/24x24/mimetypes/org.wireshark.Wireshark-mimetype.png
/usr/share/icons/hicolor/256x256/apps/org.wireshark.Wireshark.png
/usr/share/icons/hicolor/256x256/mimetypes/org.wireshark.Wireshark-mimetype.png
/usr/share/icons/hicolor/32x32/apps/org.wireshark.Wireshark.png
/usr/share/icons/hicolor/32x32/mimetypes/org.wireshark.Wireshark-mimetype.png
/usr/share/icons/hicolor/48x48/apps/org.wireshark.Wireshark.png
/usr/share/icons/hicolor/48x48/mimetypes/org.wireshark.Wireshark-mimetype.png
/usr/share/icons/hicolor/64x64/apps/org.wireshark.Wireshark.png
/usr/share/icons/hicolor/64x64/mimetypes/org.wireshark.Wireshark-mimetype.png
/usr/share/icons/hicolor/scalable/apps/org.wireshark.Wireshark.svg
/usr/share/metainfo/org.wireshark.Wireshark.metainfo.xml
/usr/share/mime-packages/org.wireshark.Wireshark.xml
/usr/share/wireshark/Acknowledgements.md
/usr/share/wireshark/COPYING
/usr/share/wireshark/cfilters
/usr/share/wireshark/colorfilters
/usr/share/wireshark/console.lua
/usr/share/wireshark/dfilter_macros
/usr/share/wireshark/dfilters
/usr/share/wireshark/diameter/AlcatelLucent.xml
/usr/share/wireshark/diameter/Cisco.xml
/usr/share/wireshark/diameter/CiscoSystems.xml
/usr/share/wireshark/diameter/Custom.xml
/usr/share/wireshark/diameter/Ericsson.xml
/usr/share/wireshark/diameter/HP.xml
/usr/share/wireshark/diameter/Huawei.xml
/usr/share/wireshark/diameter/Inovar.xml
/usr/share/wireshark/diameter/Juniper.xml
/usr/share/wireshark/diameter/Metaswitch.xml
/usr/share/wireshark/diameter/Microsoft.xml
/usr/share/wireshark/diameter/Nokia.xml
/usr/share/wireshark/diameter/NokiaSolutionsAndNetworks.xml
/usr/share/wireshark/diameter/Oracle.xml
/usr/share/wireshark/diameter/Siemens.xml
/usr/share/wireshark/diameter/Starent.xml
/usr/share/wireshark/diameter/TGPP.xml
/usr/share/wireshark/diameter/TGPP2.xml
/usr/share/wireshark/diameter/Telefonica.xml
/usr/share/wireshark/diameter/VerizonWireless.xml
/usr/share/wireshark/diameter/Vodafone.xml
/usr/share/wireshark/diameter/chargecontrol.xml
/usr/share/wireshark/diameter/dictionary.dtd
/usr/share/wireshark/diameter/dictionary.xml
/usr/share/wireshark/diameter/eap.xml
/usr/share/wireshark/diameter/etsie2e4.xml
/usr/share/wireshark/diameter/mobileipv4.xml
/usr/share/wireshark/diameter/mobileipv6.xml
/usr/share/wireshark/diameter/nasreq.xml
/usr/share/wireshark/diameter/sip.xml
/usr/share/wireshark/diameter/sunping.xml
/usr/share/wireshark/dtd_gen.lua
/usr/share/wireshark/dtds/dc.dtd
/usr/share/wireshark/dtds/itunes.dtd
/usr/share/wireshark/dtds/mscml.dtd
/usr/share/wireshark/dtds/pocsettings.dtd
/usr/share/wireshark/dtds/presence.dtd
/usr/share/wireshark/dtds/reginfo.dtd
/usr/share/wireshark/dtds/rlmi.dtd
/usr/share/wireshark/dtds/rss.dtd
/usr/share/wireshark/dtds/smil.dtd
/usr/share/wireshark/dtds/watcherinfo.dtd
/usr/share/wireshark/dtds/xcap-caps.dtd
/usr/share/wireshark/dtds/xcap-error.dtd
/usr/share/wireshark/enterprises.tsv
/usr/share/wireshark/gpl-2.0-standalone.html
/usr/share/wireshark/init.lua
/usr/share/wireshark/ipmap.html
/usr/share/wireshark/manuf
/usr/share/wireshark/pdml2html.xsl
/usr/share/wireshark/profiles/Bluetooth/colorfilters
/usr/share/wireshark/profiles/Bluetooth/preferences
/usr/share/wireshark/profiles/Classic/colorfilters
"/usr/share/wireshark/profiles/No Reassembly/preferences"
/usr/share/wireshark/radius/README.radius_dictionary
/usr/share/wireshark/radius/custom.includes
/usr/share/wireshark/radius/dictionary
/usr/share/wireshark/radius/dictionary.3com
/usr/share/wireshark/radius/dictionary.3gpp
/usr/share/wireshark/radius/dictionary.3gpp2
/usr/share/wireshark/radius/dictionary.acc
/usr/share/wireshark/radius/dictionary.acme
/usr/share/wireshark/radius/dictionary.actelis
/usr/share/wireshark/radius/dictionary.aerohive
/usr/share/wireshark/radius/dictionary.airespace
/usr/share/wireshark/radius/dictionary.alcatel
/usr/share/wireshark/radius/dictionary.alcatel-lucent.aaa
/usr/share/wireshark/radius/dictionary.alcatel.esam
/usr/share/wireshark/radius/dictionary.alcatel.sr
/usr/share/wireshark/radius/dictionary.alteon
/usr/share/wireshark/radius/dictionary.altiga
/usr/share/wireshark/radius/dictionary.alvarion
/usr/share/wireshark/radius/dictionary.alvarion.wimax.v2_2
/usr/share/wireshark/radius/dictionary.apc
/usr/share/wireshark/radius/dictionary.aptilo
/usr/share/wireshark/radius/dictionary.aptis
/usr/share/wireshark/radius/dictionary.arbor
/usr/share/wireshark/radius/dictionary.aruba
/usr/share/wireshark/radius/dictionary.ascend
/usr/share/wireshark/radius/dictionary.asn
/usr/share/wireshark/radius/dictionary.audiocodes
/usr/share/wireshark/radius/dictionary.avaya
/usr/share/wireshark/radius/dictionary.azaire
/usr/share/wireshark/radius/dictionary.bay
/usr/share/wireshark/radius/dictionary.bintec
/usr/share/wireshark/radius/dictionary.bluecoat
/usr/share/wireshark/radius/dictionary.bristol
/usr/share/wireshark/radius/dictionary.broadsoft
/usr/share/wireshark/radius/dictionary.brocade
/usr/share/wireshark/radius/dictionary.bskyb
/usr/share/wireshark/radius/dictionary.bt
/usr/share/wireshark/radius/dictionary.cablelabs
/usr/share/wireshark/radius/dictionary.cabletron
/usr/share/wireshark/radius/dictionary.camiant
/usr/share/wireshark/radius/dictionary.chillispot
/usr/share/wireshark/radius/dictionary.cisco
/usr/share/wireshark/radius/dictionary.cisco.asa
/usr/share/wireshark/radius/dictionary.cisco.bbsm
/usr/share/wireshark/radius/dictionary.cisco.vpn3000
/usr/share/wireshark/radius/dictionary.cisco.vpn5000
/usr/share/wireshark/radius/dictionary.citrix
/usr/share/wireshark/radius/dictionary.clavister
/usr/share/wireshark/radius/dictionary.cnergee
/usr/share/wireshark/radius/dictionary.colubris
/usr/share/wireshark/radius/dictionary.columbia_university
/usr/share/wireshark/radius/dictionary.compat
/usr/share/wireshark/radius/dictionary.compatible
/usr/share/wireshark/radius/dictionary.cosine
/usr/share/wireshark/radius/dictionary.dante
/usr/share/wireshark/radius/dictionary.dellemc
/usr/share/wireshark/radius/dictionary.dhcp
/usr/share/wireshark/radius/dictionary.digium
/usr/share/wireshark/radius/dictionary.dlink
/usr/share/wireshark/radius/dictionary.dragonwave
/usr/share/wireshark/radius/dictionary.efficientip
/usr/share/wireshark/radius/dictionary.eltex
/usr/share/wireshark/radius/dictionary.enterasys
/usr/share/wireshark/radius/dictionary.epygi
/usr/share/wireshark/radius/dictionary.equallogic
/usr/share/wireshark/radius/dictionary.ericsson
/usr/share/wireshark/radius/dictionary.ericsson.ab
/usr/share/wireshark/radius/dictionary.ericsson.packet.core.networks
/usr/share/wireshark/radius/dictionary.extreme
/usr/share/wireshark/radius/dictionary.f5
/usr/share/wireshark/radius/dictionary.fdxtended
/usr/share/wireshark/radius/dictionary.fortinet
/usr/share/wireshark/radius/dictionary.foundry
/usr/share/wireshark/radius/dictionary.freedhcp
/usr/share/wireshark/radius/dictionary.freeradius
/usr/share/wireshark/radius/dictionary.freeradius.internal
/usr/share/wireshark/radius/dictionary.freeswitch
/usr/share/wireshark/radius/dictionary.gandalf
/usr/share/wireshark/radius/dictionary.garderos
/usr/share/wireshark/radius/dictionary.gemtek
/usr/share/wireshark/radius/dictionary.h3c
/usr/share/wireshark/radius/dictionary.hp
/usr/share/wireshark/radius/dictionary.huawei
/usr/share/wireshark/radius/dictionary.iana
/usr/share/wireshark/radius/dictionary.identity_engines
/usr/share/wireshark/radius/dictionary.iea
/usr/share/wireshark/radius/dictionary.infoblox
/usr/share/wireshark/radius/dictionary.infonet
/usr/share/wireshark/radius/dictionary.ipunplugged
/usr/share/wireshark/radius/dictionary.issanni
/usr/share/wireshark/radius/dictionary.itk
/usr/share/wireshark/radius/dictionary.jradius
/usr/share/wireshark/radius/dictionary.juniper
/usr/share/wireshark/radius/dictionary.karlnet
/usr/share/wireshark/radius/dictionary.kineto
/usr/share/wireshark/radius/dictionary.lancom
/usr/share/wireshark/radius/dictionary.livingston
/usr/share/wireshark/radius/dictionary.localweb
/usr/share/wireshark/radius/dictionary.lucent
/usr/share/wireshark/radius/dictionary.manzara
/usr/share/wireshark/radius/dictionary.meinberg
/usr/share/wireshark/radius/dictionary.meraki
/usr/share/wireshark/radius/dictionary.merit
/usr/share/wireshark/radius/dictionary.meru
/usr/share/wireshark/radius/dictionary.microsemi
/usr/share/wireshark/radius/dictionary.microsoft
/usr/share/wireshark/radius/dictionary.mikrotik
/usr/share/wireshark/radius/dictionary.motorola
/usr/share/wireshark/radius/dictionary.motorola.wimax
/usr/share/wireshark/radius/dictionary.navini
/usr/share/wireshark/radius/dictionary.netscreen
/usr/share/wireshark/radius/dictionary.networkphysics
/usr/share/wireshark/radius/dictionary.nexans
/usr/share/wireshark/radius/dictionary.nokia
/usr/share/wireshark/radius/dictionary.nokia.conflict
/usr/share/wireshark/radius/dictionary.nomadix
/usr/share/wireshark/radius/dictionary.nortel
/usr/share/wireshark/radius/dictionary.ntua
/usr/share/wireshark/radius/dictionary.openser
/usr/share/wireshark/radius/dictionary.packeteer
/usr/share/wireshark/radius/dictionary.paloalto
/usr/share/wireshark/radius/dictionary.patton
/usr/share/wireshark/radius/dictionary.perle
/usr/share/wireshark/radius/dictionary.propel
/usr/share/wireshark/radius/dictionary.prosoft
/usr/share/wireshark/radius/dictionary.proxim
/usr/share/wireshark/radius/dictionary.purewave
/usr/share/wireshark/radius/dictionary.quiconnect
/usr/share/wireshark/radius/dictionary.quintum
/usr/share/wireshark/radius/dictionary.redcreek
/usr/share/wireshark/radius/dictionary.rfc2865
/usr/share/wireshark/radius/dictionary.rfc2866
/usr/share/wireshark/radius/dictionary.rfc2867
/usr/share/wireshark/radius/dictionary.rfc2868
/usr/share/wireshark/radius/dictionary.rfc2869
/usr/share/wireshark/radius/dictionary.rfc3162
/usr/share/wireshark/radius/dictionary.rfc3576
/usr/share/wireshark/radius/dictionary.rfc3580
/usr/share/wireshark/radius/dictionary.rfc4072
/usr/share/wireshark/radius/dictionary.rfc4372
/usr/share/wireshark/radius/dictionary.rfc4603
/usr/share/wireshark/radius/dictionary.rfc4675
/usr/share/wireshark/radius/dictionary.rfc4679
/usr/share/wireshark/radius/dictionary.rfc4818
/usr/share/wireshark/radius/dictionary.rfc4849
/usr/share/wireshark/radius/dictionary.rfc5090
/usr/share/wireshark/radius/dictionary.rfc5176
/usr/share/wireshark/radius/dictionary.rfc5447
/usr/share/wireshark/radius/dictionary.rfc5580
/usr/share/wireshark/radius/dictionary.rfc5607
/usr/share/wireshark/radius/dictionary.rfc5904
/usr/share/wireshark/radius/dictionary.rfc6519
/usr/share/wireshark/radius/dictionary.rfc6572
/usr/share/wireshark/radius/dictionary.rfc6677
/usr/share/wireshark/radius/dictionary.rfc6911
/usr/share/wireshark/radius/dictionary.rfc6929
/usr/share/wireshark/radius/dictionary.rfc6930
/usr/share/wireshark/radius/dictionary.rfc7055
/usr/share/wireshark/radius/dictionary.rfc7155
/usr/share/wireshark/radius/dictionary.rfc7268
/usr/share/wireshark/radius/dictionary.rfc7499
/usr/share/wireshark/radius/dictionary.rfc7930
/usr/share/wireshark/radius/dictionary.riverbed
/usr/share/wireshark/radius/dictionary.riverstone
/usr/share/wireshark/radius/dictionary.roaringpenguin
/usr/share/wireshark/radius/dictionary.ruckus
/usr/share/wireshark/radius/dictionary.ruggedcom
/usr/share/wireshark/radius/dictionary.sangoma
/usr/share/wireshark/radius/dictionary.sg
/usr/share/wireshark/radius/dictionary.shasta
/usr/share/wireshark/radius/dictionary.shiva
/usr/share/wireshark/radius/dictionary.siemens
/usr/share/wireshark/radius/dictionary.slipstream
/usr/share/wireshark/radius/dictionary.sofaware
/usr/share/wireshark/radius/dictionary.sonicwall
/usr/share/wireshark/radius/dictionary.springtide
/usr/share/wireshark/radius/dictionary.starent
/usr/share/wireshark/radius/dictionary.starent.vsa1
/usr/share/wireshark/radius/dictionary.surfnet
/usr/share/wireshark/radius/dictionary.symbol
/usr/share/wireshark/radius/dictionary.t_systems_nova
/usr/share/wireshark/radius/dictionary.telebit
/usr/share/wireshark/radius/dictionary.telkom
/usr/share/wireshark/radius/dictionary.terena
/usr/share/wireshark/radius/dictionary.trapeze
/usr/share/wireshark/radius/dictionary.travelping
/usr/share/wireshark/radius/dictionary.tropos
/usr/share/wireshark/radius/dictionary.ukerna
/usr/share/wireshark/radius/dictionary.unisphere
/usr/share/wireshark/radius/dictionary.unix
/usr/share/wireshark/radius/dictionary.usr
/usr/share/wireshark/radius/dictionary.utstarcom
/usr/share/wireshark/radius/dictionary.valemount
/usr/share/wireshark/radius/dictionary.verizon
/usr/share/wireshark/radius/dictionary.versanet
/usr/share/wireshark/radius/dictionary.vqp
/usr/share/wireshark/radius/dictionary.walabi
/usr/share/wireshark/radius/dictionary.waverider
/usr/share/wireshark/radius/dictionary.wichorus
/usr/share/wireshark/radius/dictionary.wimax
/usr/share/wireshark/radius/dictionary.wimax.alvarion
/usr/share/wireshark/radius/dictionary.wimax.wichorus
/usr/share/wireshark/radius/dictionary.wispr
/usr/share/wireshark/radius/dictionary.xedia
/usr/share/wireshark/radius/dictionary.xylan
/usr/share/wireshark/radius/dictionary.yubico
/usr/share/wireshark/radius/dictionary.zeus
/usr/share/wireshark/radius/dictionary.zte
/usr/share/wireshark/radius/dictionary.zyxel
/usr/share/wireshark/services
/usr/share/wireshark/smi_modules
/usr/share/wireshark/tpncp/tpncp.dat
/usr/share/wireshark/wimaxasncp/dictionary.dtd
/usr/share/wireshark/wimaxasncp/dictionary.xml
/usr/share/wireshark/wka
/usr/share/wireshark/ws.css

%files dev
%defattr(-,root,root,-)
/usr/include/wireshark/cfile.h
/usr/include/wireshark/cli_main.h
/usr/include/wireshark/epan/addr_and_mask.h
/usr/include/wireshark/epan/addr_resolv.h
/usr/include/wireshark/epan/address.h
/usr/include/wireshark/epan/address_types.h
/usr/include/wireshark/epan/afn.h
/usr/include/wireshark/epan/aftypes.h
/usr/include/wireshark/epan/app_mem_usage.h
/usr/include/wireshark/epan/arcnet_pids.h
/usr/include/wireshark/epan/arptypes.h
/usr/include/wireshark/epan/asn1.h
/usr/include/wireshark/epan/ax25_pids.h
/usr/include/wireshark/epan/bridged_pids.h
/usr/include/wireshark/epan/capture_dissectors.h
/usr/include/wireshark/epan/charsets.h
/usr/include/wireshark/epan/chdlctypes.h
/usr/include/wireshark/epan/cisco_pid.h
/usr/include/wireshark/epan/color_filters.h
/usr/include/wireshark/epan/column-info.h
/usr/include/wireshark/epan/column-utils.h
/usr/include/wireshark/epan/column.h
/usr/include/wireshark/epan/conv_id.h
/usr/include/wireshark/epan/conversation.h
/usr/include/wireshark/epan/conversation_debug.h
/usr/include/wireshark/epan/conversation_filter.h
/usr/include/wireshark/epan/conversation_table.h
/usr/include/wireshark/epan/crc10-tvb.h
/usr/include/wireshark/epan/crc16-tvb.h
/usr/include/wireshark/epan/crc32-tvb.h
/usr/include/wireshark/epan/crc6-tvb.h
/usr/include/wireshark/epan/crc8-tvb.h
/usr/include/wireshark/epan/dccpservicecodes.h
/usr/include/wireshark/epan/decode_as.h
/usr/include/wireshark/epan/dfilter/dfilter.h
/usr/include/wireshark/epan/dfilter/drange.h
/usr/include/wireshark/epan/diam_dict.h
/usr/include/wireshark/epan/disabled_protos.h
/usr/include/wireshark/epan/dissectors/cond_ace_token_enum.h
/usr/include/wireshark/epan/dissectors/file-pcapng.h
/usr/include/wireshark/epan/dissectors/file-rbm.h
/usr/include/wireshark/epan/dissectors/packet-6lowpan.h
/usr/include/wireshark/epan/dissectors/packet-a21.h
/usr/include/wireshark/epan/dissectors/packet-acdr.h
/usr/include/wireshark/epan/dissectors/packet-acp133.h
/usr/include/wireshark/epan/dissectors/packet-acse.h
/usr/include/wireshark/epan/dissectors/packet-actrace.h
/usr/include/wireshark/epan/dissectors/packet-adb_service.h
/usr/include/wireshark/epan/dissectors/packet-afp.h
/usr/include/wireshark/epan/dissectors/packet-alcap.h
/usr/include/wireshark/epan/dissectors/packet-amp.h
/usr/include/wireshark/epan/dissectors/packet-ansi_a.h
/usr/include/wireshark/epan/dissectors/packet-ansi_map.h
/usr/include/wireshark/epan/dissectors/packet-ansi_tcap.h
/usr/include/wireshark/epan/dissectors/packet-arp.h
/usr/include/wireshark/epan/dissectors/packet-asap+enrp-common.h
/usr/include/wireshark/epan/dissectors/packet-atalk.h
/usr/include/wireshark/epan/dissectors/packet-atm.h
/usr/include/wireshark/epan/dissectors/packet-atn-ulcs.h
/usr/include/wireshark/epan/dissectors/packet-autosar-ipdu-multiplexer.h
/usr/include/wireshark/epan/dissectors/packet-bacapp.h
/usr/include/wireshark/epan/dissectors/packet-bacnet.h
/usr/include/wireshark/epan/dissectors/packet-bblog.h
/usr/include/wireshark/epan/dissectors/packet-ber.h
/usr/include/wireshark/epan/dissectors/packet-bfd.h
/usr/include/wireshark/epan/dissectors/packet-bgp.h
/usr/include/wireshark/epan/dissectors/packet-bicc_mst.h
/usr/include/wireshark/epan/dissectors/packet-bluetooth.h
/usr/include/wireshark/epan/dissectors/packet-bpsec.h
/usr/include/wireshark/epan/dissectors/packet-bpv6.h
/usr/include/wireshark/epan/dissectors/packet-bpv7.h
/usr/include/wireshark/epan/dissectors/packet-bssap.h
/usr/include/wireshark/epan/dissectors/packet-bssgp.h
/usr/include/wireshark/epan/dissectors/packet-btatt.h
/usr/include/wireshark/epan/dissectors/packet-btavctp.h
/usr/include/wireshark/epan/dissectors/packet-btavdtp.h
/usr/include/wireshark/epan/dissectors/packet-btavrcp.h
/usr/include/wireshark/epan/dissectors/packet-btbredr_rf.h
/usr/include/wireshark/epan/dissectors/packet-bthci_acl.h
/usr/include/wireshark/epan/dissectors/packet-bthci_cmd.h
/usr/include/wireshark/epan/dissectors/packet-bthci_evt.h
/usr/include/wireshark/epan/dissectors/packet-bthci_iso.h
/usr/include/wireshark/epan/dissectors/packet-bthci_sco.h
/usr/include/wireshark/epan/dissectors/packet-btl2cap.h
/usr/include/wireshark/epan/dissectors/packet-btle.h
/usr/include/wireshark/epan/dissectors/packet-btrfcomm.h
/usr/include/wireshark/epan/dissectors/packet-btsdp.h
/usr/include/wireshark/epan/dissectors/packet-c1222.h
/usr/include/wireshark/epan/dissectors/packet-camel.h
/usr/include/wireshark/epan/dissectors/packet-cdt.h
/usr/include/wireshark/epan/dissectors/packet-cell_broadcast.h
/usr/include/wireshark/epan/dissectors/packet-charging_ase.h
/usr/include/wireshark/epan/dissectors/packet-chdlc.h
/usr/include/wireshark/epan/dissectors/packet-cip.h
/usr/include/wireshark/epan/dissectors/packet-cipsafety.h
/usr/include/wireshark/epan/dissectors/packet-cmip.h
/usr/include/wireshark/epan/dissectors/packet-cmp.h
/usr/include/wireshark/epan/dissectors/packet-cms.h
/usr/include/wireshark/epan/dissectors/packet-coap.h
/usr/include/wireshark/epan/dissectors/packet-cose.h
/usr/include/wireshark/epan/dissectors/packet-credssp.h
/usr/include/wireshark/epan/dissectors/packet-crmf.h
/usr/include/wireshark/epan/dissectors/packet-csn1.h
/usr/include/wireshark/epan/dissectors/packet-dap.h
/usr/include/wireshark/epan/dissectors/packet-dcc.h
/usr/include/wireshark/epan/dissectors/packet-dccp.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-browser.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-budb.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-butc.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-dce122.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-dnsserver.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-frsapi.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-frsrpc.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-netlogon.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-nt.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-pnp.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-rras.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-samr.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-spoolss.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-svcctl.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc-tapi.h
/usr/include/wireshark/epan/dissectors/packet-dcerpc.h
/usr/include/wireshark/epan/dissectors/packet-dcom-dispatch.h
/usr/include/wireshark/epan/dissectors/packet-dcom.h
/usr/include/wireshark/epan/dissectors/packet-diameter.h
/usr/include/wireshark/epan/dissectors/packet-diameter_3gpp.h
/usr/include/wireshark/epan/dissectors/packet-diffserv-mpls-common.h
/usr/include/wireshark/epan/dissectors/packet-disp.h
/usr/include/wireshark/epan/dissectors/packet-dlt.h
/usr/include/wireshark/epan/dissectors/packet-dns.h
/usr/include/wireshark/epan/dissectors/packet-docsis-tlv.h
/usr/include/wireshark/epan/dissectors/packet-doip.h
/usr/include/wireshark/epan/dissectors/packet-dop.h
/usr/include/wireshark/epan/dissectors/packet-dsp.h
/usr/include/wireshark/epan/dissectors/packet-dtls.h
/usr/include/wireshark/epan/dissectors/packet-dvbci.h
/usr/include/wireshark/epan/dissectors/packet-e164.h
/usr/include/wireshark/epan/dissectors/packet-e1ap.h
/usr/include/wireshark/epan/dissectors/packet-e212.h
/usr/include/wireshark/epan/dissectors/packet-eapol.h
/usr/include/wireshark/epan/dissectors/packet-edonkey.h
/usr/include/wireshark/epan/dissectors/packet-eigrp.h
/usr/include/wireshark/epan/dissectors/packet-enip.h
/usr/include/wireshark/epan/dissectors/packet-epl.h
/usr/include/wireshark/epan/dissectors/packet-epmd.h
/usr/include/wireshark/epan/dissectors/packet-erf.h
/usr/include/wireshark/epan/dissectors/packet-ess.h
/usr/include/wireshark/epan/dissectors/packet-eth.h
/usr/include/wireshark/epan/dissectors/packet-f1ap.h
/usr/include/wireshark/epan/dissectors/packet-f5ethtrailer.h
/usr/include/wireshark/epan/dissectors/packet-fc.h
/usr/include/wireshark/epan/dissectors/packet-fcbls.h
/usr/include/wireshark/epan/dissectors/packet-fcct.h
/usr/include/wireshark/epan/dissectors/packet-fcels.h
/usr/include/wireshark/epan/dissectors/packet-fcfcs.h
/usr/include/wireshark/epan/dissectors/packet-fcfzs.h
/usr/include/wireshark/epan/dissectors/packet-fclctl.h
/usr/include/wireshark/epan/dissectors/packet-fcsb3.h
/usr/include/wireshark/epan/dissectors/packet-fcswils.h
/usr/include/wireshark/epan/dissectors/packet-ff.h
/usr/include/wireshark/epan/dissectors/packet-fix.h
/usr/include/wireshark/epan/dissectors/packet-flexray.h
/usr/include/wireshark/epan/dissectors/packet-fmp.h
/usr/include/wireshark/epan/dissectors/packet-frame.h
/usr/include/wireshark/epan/dissectors/packet-ftam.h
/usr/include/wireshark/epan/dissectors/packet-ftdi-ft.h
/usr/include/wireshark/epan/dissectors/packet-gdt.h
/usr/include/wireshark/epan/dissectors/packet-geonw.h
/usr/include/wireshark/epan/dissectors/packet-giop.h
/usr/include/wireshark/epan/dissectors/packet-gluster.h
/usr/include/wireshark/epan/dissectors/packet-gmr1_common.h
/usr/include/wireshark/epan/dissectors/packet-gmr1_rr.h
/usr/include/wireshark/epan/dissectors/packet-gprscdr.h
/usr/include/wireshark/epan/dissectors/packet-gre.h
/usr/include/wireshark/epan/dissectors/packet-gsm_a_common.h
/usr/include/wireshark/epan/dissectors/packet-gsm_a_rr.h
/usr/include/wireshark/epan/dissectors/packet-gsm_map.h
/usr/include/wireshark/epan/dissectors/packet-gsm_rlcmac.h
/usr/include/wireshark/epan/dissectors/packet-gsm_sms.h
/usr/include/wireshark/epan/dissectors/packet-gsmtap.h
/usr/include/wireshark/epan/dissectors/packet-gssapi.h
/usr/include/wireshark/epan/dissectors/packet-gtp.h
/usr/include/wireshark/epan/dissectors/packet-gtpv2.h
/usr/include/wireshark/epan/dissectors/packet-h223.h
/usr/include/wireshark/epan/dissectors/packet-h225.h
/usr/include/wireshark/epan/dissectors/packet-h235.h
/usr/include/wireshark/epan/dissectors/packet-h245.h
/usr/include/wireshark/epan/dissectors/packet-h248.h
/usr/include/wireshark/epan/dissectors/packet-h263.h
/usr/include/wireshark/epan/dissectors/packet-h264.h
/usr/include/wireshark/epan/dissectors/packet-h265.h
/usr/include/wireshark/epan/dissectors/packet-h323.h
/usr/include/wireshark/epan/dissectors/packet-h450-ros.h
/usr/include/wireshark/epan/dissectors/packet-hpext.h
/usr/include/wireshark/epan/dissectors/packet-http.h
/usr/include/wireshark/epan/dissectors/packet-http2.h
/usr/include/wireshark/epan/dissectors/packet-iana-oui.h
/usr/include/wireshark/epan/dissectors/packet-iax2.h
/usr/include/wireshark/epan/dissectors/packet-icmp.h
/usr/include/wireshark/epan/dissectors/packet-idmp.h
/usr/include/wireshark/epan/dissectors/packet-idp.h
/usr/include/wireshark/epan/dissectors/packet-ieee1609dot2.h
/usr/include/wireshark/epan/dissectors/packet-ieee80211-radio.h
/usr/include/wireshark/epan/dissectors/packet-ieee80211-radiotap-defs.h
/usr/include/wireshark/epan/dissectors/packet-ieee80211-radiotap-iter.h
/usr/include/wireshark/epan/dissectors/packet-ieee80211.h
/usr/include/wireshark/epan/dissectors/packet-ieee802154.h
/usr/include/wireshark/epan/dissectors/packet-ieee8023.h
/usr/include/wireshark/epan/dissectors/packet-ieee802a.h
/usr/include/wireshark/epan/dissectors/packet-igmp.h
/usr/include/wireshark/epan/dissectors/packet-imf.h
/usr/include/wireshark/epan/dissectors/packet-inap.h
/usr/include/wireshark/epan/dissectors/packet-infiniband.h
/usr/include/wireshark/epan/dissectors/packet-ip.h
/usr/include/wireshark/epan/dissectors/packet-ipmi.h
/usr/include/wireshark/epan/dissectors/packet-ipsec.h
/usr/include/wireshark/epan/dissectors/packet-ipx.h
/usr/include/wireshark/epan/dissectors/packet-isakmp.h
/usr/include/wireshark/epan/dissectors/packet-isis-clv.h
/usr/include/wireshark/epan/dissectors/packet-isis.h
/usr/include/wireshark/epan/dissectors/packet-isl.h
/usr/include/wireshark/epan/dissectors/packet-iso10681.h
/usr/include/wireshark/epan/dissectors/packet-iso15765.h
/usr/include/wireshark/epan/dissectors/packet-isup.h
/usr/include/wireshark/epan/dissectors/packet-its.h
/usr/include/wireshark/epan/dissectors/packet-iwarp-ddp-rdmap.h
/usr/include/wireshark/epan/dissectors/packet-juniper.h
/usr/include/wireshark/epan/dissectors/packet-jxta.h
/usr/include/wireshark/epan/dissectors/packet-kerberos.h
/usr/include/wireshark/epan/dissectors/packet-knxip.h
/usr/include/wireshark/epan/dissectors/packet-knxip_decrypt.h
/usr/include/wireshark/epan/dissectors/packet-l2tp.h
/usr/include/wireshark/epan/dissectors/packet-lapdm.h
/usr/include/wireshark/epan/dissectors/packet-lbm.h
/usr/include/wireshark/epan/dissectors/packet-lbtrm.h
/usr/include/wireshark/epan/dissectors/packet-lbtru.h
/usr/include/wireshark/epan/dissectors/packet-lbttcp.h
/usr/include/wireshark/epan/dissectors/packet-lcsap.h
/usr/include/wireshark/epan/dissectors/packet-ldap.h
/usr/include/wireshark/epan/dissectors/packet-ldp.h
/usr/include/wireshark/epan/dissectors/packet-lin.h
/usr/include/wireshark/epan/dissectors/packet-link16.h
/usr/include/wireshark/epan/dissectors/packet-lisp.h
/usr/include/wireshark/epan/dissectors/packet-llc.h
/usr/include/wireshark/epan/dissectors/packet-lnet.h
/usr/include/wireshark/epan/dissectors/packet-logotypecertextn.h
/usr/include/wireshark/epan/dissectors/packet-lpp.h
/usr/include/wireshark/epan/dissectors/packet-lppa.h
/usr/include/wireshark/epan/dissectors/packet-lte-rrc.h
/usr/include/wireshark/epan/dissectors/packet-mac-lte.h
/usr/include/wireshark/epan/dissectors/packet-mausb.h
/usr/include/wireshark/epan/dissectors/packet-mbim.h
/usr/include/wireshark/epan/dissectors/packet-mbtcp.h
/usr/include/wireshark/epan/dissectors/packet-mgcp.h
/usr/include/wireshark/epan/dissectors/packet-mle.h
/usr/include/wireshark/epan/dissectors/packet-mms.h
/usr/include/wireshark/epan/dissectors/packet-mount.h
/usr/include/wireshark/epan/dissectors/packet-mp4ves.h
/usr/include/wireshark/epan/dissectors/packet-mpeg-descriptor.h
/usr/include/wireshark/epan/dissectors/packet-mpeg-sect.h
/usr/include/wireshark/epan/dissectors/packet-mpls.h
/usr/include/wireshark/epan/dissectors/packet-mq.h
/usr/include/wireshark/epan/dissectors/packet-msrp.h
/usr/include/wireshark/epan/dissectors/packet-mstp.h
/usr/include/wireshark/epan/dissectors/packet-mtp3.h
/usr/include/wireshark/epan/dissectors/packet-nbap.h
/usr/include/wireshark/epan/dissectors/packet-ncp-int.h
/usr/include/wireshark/epan/dissectors/packet-ncp-nmas.h
/usr/include/wireshark/epan/dissectors/packet-ncp-sss.h
/usr/include/wireshark/epan/dissectors/packet-ndmp.h
/usr/include/wireshark/epan/dissectors/packet-ndps.h
/usr/include/wireshark/epan/dissectors/packet-netbios.h
/usr/include/wireshark/epan/dissectors/packet-netlink.h
/usr/include/wireshark/epan/dissectors/packet-nfs.h
/usr/include/wireshark/epan/dissectors/packet-ngap.h
/usr/include/wireshark/epan/dissectors/packet-nisplus.h
/usr/include/wireshark/epan/dissectors/packet-nlm.h
/usr/include/wireshark/epan/dissectors/packet-nr-rrc.h
/usr/include/wireshark/epan/dissectors/packet-nrppa.h
/usr/include/wireshark/epan/dissectors/packet-nsh.h
/usr/include/wireshark/epan/dissectors/packet-ntlmssp.h
/usr/include/wireshark/epan/dissectors/packet-ntp.h
/usr/include/wireshark/epan/dissectors/packet-nvme.h
/usr/include/wireshark/epan/dissectors/packet-ocsp.h
/usr/include/wireshark/epan/dissectors/packet-oer.h
/usr/include/wireshark/epan/dissectors/packet-opensafety.h
/usr/include/wireshark/epan/dissectors/packet-oscore.h
/usr/include/wireshark/epan/dissectors/packet-osi-options.h
/usr/include/wireshark/epan/dissectors/packet-osi.h
/usr/include/wireshark/epan/dissectors/packet-p1.h
/usr/include/wireshark/epan/dissectors/packet-p22.h
/usr/include/wireshark/epan/dissectors/packet-p7.h
/usr/include/wireshark/epan/dissectors/packet-p772.h
/usr/include/wireshark/epan/dissectors/packet-pcap_pktdata.h
/usr/include/wireshark/epan/dissectors/packet-pcnfsd.h
/usr/include/wireshark/epan/dissectors/packet-pdcp-lte.h
/usr/include/wireshark/epan/dissectors/packet-pdcp-nr.h
/usr/include/wireshark/epan/dissectors/packet-pdu-transport.h
/usr/include/wireshark/epan/dissectors/packet-per.h
/usr/include/wireshark/epan/dissectors/packet-pkcs1.h
/usr/include/wireshark/epan/dissectors/packet-pkcs12.h
/usr/include/wireshark/epan/dissectors/packet-pkinit.h
/usr/include/wireshark/epan/dissectors/packet-pkix1explicit.h
/usr/include/wireshark/epan/dissectors/packet-pkix1implicit.h
/usr/include/wireshark/epan/dissectors/packet-pkixac.h
/usr/include/wireshark/epan/dissectors/packet-pkixproxy.h
/usr/include/wireshark/epan/dissectors/packet-pkixqualified.h
/usr/include/wireshark/epan/dissectors/packet-pkixtsp.h
/usr/include/wireshark/epan/dissectors/packet-portmap.h
/usr/include/wireshark/epan/dissectors/packet-ppi-geolocation-common.h
/usr/include/wireshark/epan/dissectors/packet-ppp.h
/usr/include/wireshark/epan/dissectors/packet-pres.h
/usr/include/wireshark/epan/dissectors/packet-ptp.h
/usr/include/wireshark/epan/dissectors/packet-ptpip.h
/usr/include/wireshark/epan/dissectors/packet-pw-atm.h
/usr/include/wireshark/epan/dissectors/packet-pw-common.h
/usr/include/wireshark/epan/dissectors/packet-q708.h
/usr/include/wireshark/epan/dissectors/packet-q931.h
/usr/include/wireshark/epan/dissectors/packet-q932.h
/usr/include/wireshark/epan/dissectors/packet-qsig.h
/usr/include/wireshark/epan/dissectors/packet-quic.h
/usr/include/wireshark/epan/dissectors/packet-radius.h
/usr/include/wireshark/epan/dissectors/packet-raknet.h
/usr/include/wireshark/epan/dissectors/packet-ranap.h
/usr/include/wireshark/epan/dissectors/packet-rdm.h
/usr/include/wireshark/epan/dissectors/packet-rdt.h
/usr/include/wireshark/epan/dissectors/packet-reload.h
/usr/include/wireshark/epan/dissectors/packet-rlc-lte.h
/usr/include/wireshark/epan/dissectors/packet-rlc-nr.h
/usr/include/wireshark/epan/dissectors/packet-rmi.h
/usr/include/wireshark/epan/dissectors/packet-rmt-common.h
/usr/include/wireshark/epan/dissectors/packet-rohc.h
/usr/include/wireshark/epan/dissectors/packet-ros.h
/usr/include/wireshark/epan/dissectors/packet-rpc.h
/usr/include/wireshark/epan/dissectors/packet-rpcrdma.h
/usr/include/wireshark/epan/dissectors/packet-rrc.h
/usr/include/wireshark/epan/dissectors/packet-rsvp.h
/usr/include/wireshark/epan/dissectors/packet-rtcp.h
/usr/include/wireshark/epan/dissectors/packet-rtp-events.h
/usr/include/wireshark/epan/dissectors/packet-rtp.h
/usr/include/wireshark/epan/dissectors/packet-rtse.h
/usr/include/wireshark/epan/dissectors/packet-rtsp.h
/usr/include/wireshark/epan/dissectors/packet-rx.h
/usr/include/wireshark/epan/dissectors/packet-s1ap.h
/usr/include/wireshark/epan/dissectors/packet-s5066sis.h
/usr/include/wireshark/epan/dissectors/packet-s7comm.h
/usr/include/wireshark/epan/dissectors/packet-s7comm_szl_ids.h
/usr/include/wireshark/epan/dissectors/packet-sccp.h
/usr/include/wireshark/epan/dissectors/packet-scsi-mmc.h
/usr/include/wireshark/epan/dissectors/packet-scsi-osd.h
/usr/include/wireshark/epan/dissectors/packet-scsi-sbc.h
/usr/include/wireshark/epan/dissectors/packet-scsi-smc.h
/usr/include/wireshark/epan/dissectors/packet-scsi-ssc.h
/usr/include/wireshark/epan/dissectors/packet-scsi.h
/usr/include/wireshark/epan/dissectors/packet-sctp.h
/usr/include/wireshark/epan/dissectors/packet-sdp.h
/usr/include/wireshark/epan/dissectors/packet-ses.h
/usr/include/wireshark/epan/dissectors/packet-sflow.h
/usr/include/wireshark/epan/dissectors/packet-sip.h
/usr/include/wireshark/epan/dissectors/packet-skinny.h
/usr/include/wireshark/epan/dissectors/packet-sll.h
/usr/include/wireshark/epan/dissectors/packet-smb-browse.h
/usr/include/wireshark/epan/dissectors/packet-smb-common.h
/usr/include/wireshark/epan/dissectors/packet-smb-mailslot.h
/usr/include/wireshark/epan/dissectors/packet-smb-pipe.h
/usr/include/wireshark/epan/dissectors/packet-smb-sidsnooping.h
/usr/include/wireshark/epan/dissectors/packet-smb.h
/usr/include/wireshark/epan/dissectors/packet-smb2.h
/usr/include/wireshark/epan/dissectors/packet-smpp.h
/usr/include/wireshark/epan/dissectors/packet-smrse.h
/usr/include/wireshark/epan/dissectors/packet-snmp.h
/usr/include/wireshark/epan/dissectors/packet-socketcan.h
/usr/include/wireshark/epan/dissectors/packet-someip.h
/usr/include/wireshark/epan/dissectors/packet-spice.h
/usr/include/wireshark/epan/dissectors/packet-sprt.h
/usr/include/wireshark/epan/dissectors/packet-sscop.h
/usr/include/wireshark/epan/dissectors/packet-stat-notify.h
/usr/include/wireshark/epan/dissectors/packet-stat.h
/usr/include/wireshark/epan/dissectors/packet-sv.h
/usr/include/wireshark/epan/dissectors/packet-syslog.h
/usr/include/wireshark/epan/dissectors/packet-t124.h
/usr/include/wireshark/epan/dissectors/packet-t30.h
/usr/include/wireshark/epan/dissectors/packet-t38.h
/usr/include/wireshark/epan/dissectors/packet-tacacs.h
/usr/include/wireshark/epan/dissectors/packet-tcap.h
/usr/include/wireshark/epan/dissectors/packet-tcp.h
/usr/include/wireshark/epan/dissectors/packet-tcpcl.h
/usr/include/wireshark/epan/dissectors/packet-tecmp.h
/usr/include/wireshark/epan/dissectors/packet-tetra.h
/usr/include/wireshark/epan/dissectors/packet-thrift.h
/usr/include/wireshark/epan/dissectors/packet-tls-utils.h
/usr/include/wireshark/epan/dissectors/packet-tls.h
/usr/include/wireshark/epan/dissectors/packet-tn3270.h
/usr/include/wireshark/epan/dissectors/packet-tn5250.h
/usr/include/wireshark/epan/dissectors/packet-tpkt.h
/usr/include/wireshark/epan/dissectors/packet-tr.h
/usr/include/wireshark/epan/dissectors/packet-tte.h
/usr/include/wireshark/epan/dissectors/packet-ua.h
/usr/include/wireshark/epan/dissectors/packet-uaudp.h
/usr/include/wireshark/epan/dissectors/packet-uavcan-dsdl.h
/usr/include/wireshark/epan/dissectors/packet-ubertooth.h
/usr/include/wireshark/epan/dissectors/packet-udp.h
/usr/include/wireshark/epan/dissectors/packet-uds.h
/usr/include/wireshark/epan/dissectors/packet-umts_fp.h
/usr/include/wireshark/epan/dissectors/packet-umts_mac.h
/usr/include/wireshark/epan/dissectors/packet-umts_rlc.h
/usr/include/wireshark/epan/dissectors/packet-usb-hid.h
/usr/include/wireshark/epan/dissectors/packet-usb.h
/usr/include/wireshark/epan/dissectors/packet-usbip.h
/usr/include/wireshark/epan/dissectors/packet-vxlan.h
/usr/include/wireshark/epan/dissectors/packet-wap.h
/usr/include/wireshark/epan/dissectors/packet-wccp.h
/usr/include/wireshark/epan/dissectors/packet-windows-common.h
/usr/include/wireshark/epan/dissectors/packet-wlancertextn.h
/usr/include/wireshark/epan/dissectors/packet-wps.h
/usr/include/wireshark/epan/dissectors/packet-wsp.h
/usr/include/wireshark/epan/dissectors/packet-wtls.h
/usr/include/wireshark/epan/dissectors/packet-wtp.h
/usr/include/wireshark/epan/dissectors/packet-x11-keysymdef.h
/usr/include/wireshark/epan/dissectors/packet-x11.h
/usr/include/wireshark/epan/dissectors/packet-x2ap.h
/usr/include/wireshark/epan/dissectors/packet-x509af.h
/usr/include/wireshark/epan/dissectors/packet-x509ce.h
/usr/include/wireshark/epan/dissectors/packet-x509if.h
/usr/include/wireshark/epan/dissectors/packet-x509sat.h
/usr/include/wireshark/epan/dissectors/packet-xml.h
/usr/include/wireshark/epan/dissectors/packet-xmpp-conference.h
/usr/include/wireshark/epan/dissectors/packet-xmpp-core.h
/usr/include/wireshark/epan/dissectors/packet-xmpp-gtalk.h
/usr/include/wireshark/epan/dissectors/packet-xmpp-jingle.h
/usr/include/wireshark/epan/dissectors/packet-xmpp-other.h
/usr/include/wireshark/epan/dissectors/packet-xmpp-utils.h
/usr/include/wireshark/epan/dissectors/packet-xmpp.h
/usr/include/wireshark/epan/dissectors/packet-xnap.h
/usr/include/wireshark/epan/dissectors/packet-ypbind.h
/usr/include/wireshark/epan/dissectors/packet-yppasswd.h
/usr/include/wireshark/epan/dissectors/packet-ypserv.h
/usr/include/wireshark/epan/dissectors/packet-ypxfr.h
/usr/include/wireshark/epan/dissectors/packet-zbee-aps.h
/usr/include/wireshark/epan/dissectors/packet-zbee-nwk.h
/usr/include/wireshark/epan/dissectors/packet-zbee-security.h
/usr/include/wireshark/epan/dissectors/packet-zbee-zcl.h
/usr/include/wireshark/epan/dissectors/packet-zbee-zdp.h
/usr/include/wireshark/epan/dissectors/packet-zbee.h
/usr/include/wireshark/epan/dissectors/packet-ziop.h
/usr/include/wireshark/epan/dtd.h
/usr/include/wireshark/epan/dtd_parse.h
/usr/include/wireshark/epan/dvb_chartbl.h
/usr/include/wireshark/epan/eap.h
/usr/include/wireshark/epan/eapol_keydes_types.h
/usr/include/wireshark/epan/epan.h
/usr/include/wireshark/epan/epan_dissect.h
/usr/include/wireshark/epan/etypes.h
/usr/include/wireshark/epan/ex-opt.h
/usr/include/wireshark/epan/except.h
/usr/include/wireshark/epan/exceptions.h
/usr/include/wireshark/epan/expert.h
/usr/include/wireshark/epan/export_object.h
/usr/include/wireshark/epan/exported_pdu.h
/usr/include/wireshark/epan/filter_expressions.h
/usr/include/wireshark/epan/follow.h
/usr/include/wireshark/epan/frame_data.h
/usr/include/wireshark/epan/frame_data_sequence.h
/usr/include/wireshark/epan/ftypes/ftypes.h
/usr/include/wireshark/epan/funnel.h
/usr/include/wireshark/epan/golay.h
/usr/include/wireshark/epan/guid-utils.h
/usr/include/wireshark/epan/iana_charsets.h
/usr/include/wireshark/epan/iax2_codec_type.h
/usr/include/wireshark/epan/in_cksum.h
/usr/include/wireshark/epan/introspection.h
/usr/include/wireshark/epan/ip_opts.h
/usr/include/wireshark/epan/ipproto.h
/usr/include/wireshark/epan/ipv4.h
/usr/include/wireshark/epan/ipv6.h
/usr/include/wireshark/epan/lapd_sapi.h
/usr/include/wireshark/epan/llcsaps.h
/usr/include/wireshark/epan/maxmind_db.h
/usr/include/wireshark/epan/media_params.h
/usr/include/wireshark/epan/next_tvb.h
/usr/include/wireshark/epan/nlpid.h
/usr/include/wireshark/epan/oids.h
/usr/include/wireshark/epan/osi-utils.h
/usr/include/wireshark/epan/oui.h
/usr/include/wireshark/epan/packet.h
/usr/include/wireshark/epan/packet_info.h
/usr/include/wireshark/epan/params.h
/usr/include/wireshark/epan/pci-ids.h
/usr/include/wireshark/epan/plugin_if.h
/usr/include/wireshark/epan/ppptypes.h
/usr/include/wireshark/epan/prefs-int.h
/usr/include/wireshark/epan/prefs.h
/usr/include/wireshark/epan/print.h
/usr/include/wireshark/epan/print_stream.h
/usr/include/wireshark/epan/proto.h
/usr/include/wireshark/epan/proto_data.h
/usr/include/wireshark/epan/ps.h
/usr/include/wireshark/epan/ptvcursor.h
/usr/include/wireshark/epan/range.h
/usr/include/wireshark/epan/reassemble.h
/usr/include/wireshark/epan/reedsolomon.h
/usr/include/wireshark/epan/register.h
/usr/include/wireshark/epan/req_resp_hdrs.h
/usr/include/wireshark/epan/rtd_table.h
/usr/include/wireshark/epan/rtp_pt.h
/usr/include/wireshark/epan/sctpppids.h
/usr/include/wireshark/epan/secrets.h
/usr/include/wireshark/epan/show_exception.h
/usr/include/wireshark/epan/slow_protocol_subtypes.h
/usr/include/wireshark/epan/sminmpec.h
/usr/include/wireshark/epan/srt_table.h
/usr/include/wireshark/epan/stat_groups.h
/usr/include/wireshark/epan/stat_tap_ui.h
/usr/include/wireshark/epan/stats_tree.h
/usr/include/wireshark/epan/stats_tree_priv.h
/usr/include/wireshark/epan/stream.h
/usr/include/wireshark/epan/strutil.h
/usr/include/wireshark/epan/t35.h
/usr/include/wireshark/epan/tap-voip.h
/usr/include/wireshark/epan/tap.h
/usr/include/wireshark/epan/tfs.h
/usr/include/wireshark/epan/timestamp.h
/usr/include/wireshark/epan/timestats.h
/usr/include/wireshark/epan/to_str.h
/usr/include/wireshark/epan/tvbparse.h
/usr/include/wireshark/epan/tvbuff-int.h
/usr/include/wireshark/epan/tvbuff.h
/usr/include/wireshark/epan/uat-int.h
/usr/include/wireshark/epan/uat.h
/usr/include/wireshark/epan/unit_strings.h
/usr/include/wireshark/epan/value_string.h
/usr/include/wireshark/epan/wmem_scopes.h
/usr/include/wireshark/epan/wscbor.h
/usr/include/wireshark/epan/x264_prt_id.h
/usr/include/wireshark/epan/xdlc.h
/usr/include/wireshark/file.h
/usr/include/wireshark/wireshark.h
/usr/include/wireshark/wiretap/file_wrappers.h
/usr/include/wireshark/wiretap/merge.h
/usr/include/wireshark/wiretap/pcap-encap.h
/usr/include/wireshark/wiretap/pcapng_module.h
/usr/include/wireshark/wiretap/secrets-types.h
/usr/include/wireshark/wiretap/wtap.h
/usr/include/wireshark/wiretap/wtap_modules.h
/usr/include/wireshark/wiretap/wtap_opttypes.h
/usr/include/wireshark/ws_attributes.h
/usr/include/wireshark/ws_compiler_tests.h
/usr/include/wireshark/ws_diag_control.h
/usr/include/wireshark/ws_log_defs.h
/usr/include/wireshark/ws_posix_compat.h
/usr/include/wireshark/ws_symbol_export.h
/usr/include/wireshark/ws_version.h
/usr/include/wireshark/wsutil/802_11-utils.h
/usr/include/wireshark/wsutil/adler32.h
/usr/include/wireshark/wsutil/base32.h
/usr/include/wireshark/wsutil/bits_count_ones.h
/usr/include/wireshark/wsutil/bits_ctz.h
/usr/include/wireshark/wsutil/bitswap.h
/usr/include/wireshark/wsutil/buffer.h
/usr/include/wireshark/wsutil/codecs.h
/usr/include/wireshark/wsutil/color.h
/usr/include/wireshark/wsutil/cpu_info.h
/usr/include/wireshark/wsutil/crash_info.h
/usr/include/wireshark/wsutil/crc10.h
/usr/include/wireshark/wsutil/crc11.h
/usr/include/wireshark/wsutil/crc16-plain.h
/usr/include/wireshark/wsutil/crc16.h
/usr/include/wireshark/wsutil/crc32.h
/usr/include/wireshark/wsutil/crc5.h
/usr/include/wireshark/wsutil/crc6.h
/usr/include/wireshark/wsutil/crc7.h
/usr/include/wireshark/wsutil/crc8.h
/usr/include/wireshark/wsutil/curve25519.h
/usr/include/wireshark/wsutil/eax.h
/usr/include/wireshark/wsutil/epochs.h
/usr/include/wireshark/wsutil/exported_pdu_tlvs.h
/usr/include/wireshark/wsutil/feature_list.h
/usr/include/wireshark/wsutil/filesystem.h
/usr/include/wireshark/wsutil/g711.h
/usr/include/wireshark/wsutil/glib-compat.h
/usr/include/wireshark/wsutil/inet_addr.h
/usr/include/wireshark/wsutil/inet_ipv4.h
/usr/include/wireshark/wsutil/inet_ipv6.h
/usr/include/wireshark/wsutil/interface.h
/usr/include/wireshark/wsutil/jsmn.h
/usr/include/wireshark/wsutil/json_dumper.h
/usr/include/wireshark/wsutil/mpeg-audio.h
/usr/include/wireshark/wsutil/netlink.h
/usr/include/wireshark/wsutil/nstime.h
/usr/include/wireshark/wsutil/os_version_info.h
/usr/include/wireshark/wsutil/pint.h
/usr/include/wireshark/wsutil/please_report_bug.h
/usr/include/wireshark/wsutil/pow2.h
/usr/include/wireshark/wsutil/privileges.h
/usr/include/wireshark/wsutil/processes.h
/usr/include/wireshark/wsutil/regex.h
/usr/include/wireshark/wsutil/report_message.h
/usr/include/wireshark/wsutil/sign_ext.h
/usr/include/wireshark/wsutil/sober128.h
/usr/include/wireshark/wsutil/socket.h
/usr/include/wireshark/wsutil/str_util.h
/usr/include/wireshark/wsutil/strnatcmp.h
/usr/include/wireshark/wsutil/strtoi.h
/usr/include/wireshark/wsutil/tempfile.h
/usr/include/wireshark/wsutil/time_util.h
/usr/include/wireshark/wsutil/to_str.h
/usr/include/wireshark/wsutil/type_util.h
/usr/include/wireshark/wsutil/unicode-utils.h
/usr/include/wireshark/wsutil/utf8_entities.h
/usr/include/wireshark/wsutil/wmem/wmem.h
/usr/include/wireshark/wsutil/wmem/wmem_array.h
/usr/include/wireshark/wsutil/wmem/wmem_core.h
/usr/include/wireshark/wsutil/wmem/wmem_interval_tree.h
/usr/include/wireshark/wsutil/wmem/wmem_list.h
/usr/include/wireshark/wsutil/wmem/wmem_map.h
/usr/include/wireshark/wsutil/wmem/wmem_miscutl.h
/usr/include/wireshark/wsutil/wmem/wmem_multimap.h
/usr/include/wireshark/wsutil/wmem/wmem_queue.h
/usr/include/wireshark/wsutil/wmem/wmem_stack.h
/usr/include/wireshark/wsutil/wmem/wmem_strbuf.h
/usr/include/wireshark/wsutil/wmem/wmem_strutl.h
/usr/include/wireshark/wsutil/wmem/wmem_tree.h
/usr/include/wireshark/wsutil/wmem/wmem_user_cb.h
/usr/include/wireshark/wsutil/ws_assert.h
/usr/include/wireshark/wsutil/ws_cpuid.h
/usr/include/wireshark/wsutil/ws_getopt.h
/usr/include/wireshark/wsutil/ws_mempbrk.h
/usr/include/wireshark/wsutil/ws_mempbrk_int.h
/usr/include/wireshark/wsutil/ws_pipe.h
/usr/include/wireshark/wsutil/ws_return.h
/usr/include/wireshark/wsutil/ws_roundup.h
/usr/include/wireshark/wsutil/wsgcrypt.h
/usr/include/wireshark/wsutil/wsjson.h
/usr/include/wireshark/wsutil/wslog.h
/usr/include/wireshark/wsutil/xtea.h
/usr/lib64/libwireshark.so
/usr/lib64/libwiretap.so
/usr/lib64/libwsutil.so
/usr/lib64/pkgconfig/wireshark.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libwireshark.so.16
/usr/lib64/libwireshark.so.16.0.0
/usr/lib64/libwiretap.so.13
/usr/lib64/libwiretap.so.13.0.0
/usr/lib64/libwsutil.so.14
/usr/lib64/libwsutil.so.14.0.0
/usr/lib64/wireshark/plugins/4.0/codecs/g711.so
/usr/lib64/wireshark/plugins/4.0/codecs/l16mono.so
/usr/lib64/wireshark/plugins/4.0/codecs/opus_dec.so
/usr/lib64/wireshark/plugins/4.0/codecs/sbc.so
/usr/lib64/wireshark/plugins/4.0/epan/ethercat.so
/usr/lib64/wireshark/plugins/4.0/epan/gryphon.so
/usr/lib64/wireshark/plugins/4.0/epan/irda.so
/usr/lib64/wireshark/plugins/4.0/epan/mate.so
/usr/lib64/wireshark/plugins/4.0/epan/opcua.so
/usr/lib64/wireshark/plugins/4.0/epan/profinet.so
/usr/lib64/wireshark/plugins/4.0/epan/stats_tree.so
/usr/lib64/wireshark/plugins/4.0/epan/transum.so
/usr/lib64/wireshark/plugins/4.0/epan/unistim.so
/usr/lib64/wireshark/plugins/4.0/epan/wimax.so
/usr/lib64/wireshark/plugins/4.0/epan/wimaxasncp.so
/usr/lib64/wireshark/plugins/4.0/epan/wimaxmacphy.so
/usr/lib64/wireshark/plugins/4.0/wiretap/usbdump.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/wireshark/41bb27089429d9d6febf18e4237cf04d81fcc737
/usr/share/package-licenses/wireshark/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/wireshark/6a24215d6bbdeb8e9b97926525bcf1958dda4e86
/usr/share/package-licenses/wireshark/95e0d72b02cd8da759ea37b4b9dd8c759c5cad72
/usr/share/package-licenses/wireshark/a20d2f6f5e7e9eb06617df3b88af6192a8147307
/usr/share/package-licenses/wireshark/fad0e142195689a22e56df66f20dbd840679adb9
